import { create } from 'zustand'
import { layers, type CutShape, type Layer, type LayerTransform } from '../mock/project'

export type Mode = 'compose' | 'stage'
export type Tab = 'layers' | 'assets' | 'tools'
export type DialogName = 'new' | 'import' | 'preview' | 'export' | 'shortcuts' | 'delete' | null
export type ReorderMode = 'cascade' | 'split'
type SavedProject = { version: number; sceneLayers: Layer[]; reorderMode: ReorderMode }
const load = (): SavedProject | null => { try { const raw = typeof window !== 'undefined' && window.localStorage.getItem('papercut.prototype.project.v1'); return raw ? JSON.parse(raw) : null } catch { return null } }
const saved = load()
const cloneLayers = () => (saved?.sceneLayers ?? layers).map(l => ({ ...l, transform: { ...l.transform }, cuts: l.cuts ?? [], pieces: l.pieces ?? [] }))

type UIState = {
  mode: Mode; tab: Tab; tool: string; selected: string; selectedPieces: string[]; sketch: CutShape[]; dialog: DialogName; time: number; playing: boolean; grid: boolean; safeFrame: boolean; material: string; expanded: Record<string, boolean>; keyframes: string[]; sceneLayers: Layer[]; orbit: { x: number; y: number }; zoom: number; reorderMode: ReorderMode; saveStatus: 'saved' | 'unsaved';
  setMode:(a: Mode) => void; setTab:(a: Tab) => void; setTool:(a: string) => void; select:(a: string) => void; togglePieceSelection:(a: string, shift: boolean) => void; setDialog:(a: DialogName) => void; setTime:(a: number) => void; togglePlaying:() => void; toggleGrid:() => void; toggleSafe:() => void; setMaterial:(a: string) => void; toggleExpanded:(a: string) => void; toggleKey:(a: string) => void; addLayer:() => void; removeLayer:(a: string) => void; setLayerDepth:(a: string, b: number)=> void; setLayerTransform:(a: string, b: keyof LayerTransform, c: number)=> void; toggleLayerVisibility:(a: string)=> void; renameLayer:(a: string,b: string)=> void; setLayerColor:(a: string,b: string)=> void; reorderLayer:(a: string,b: string)=> void; setReorderMode:(a: ReorderMode)=> void; setOrbit:(a: {x:number;y:number})=> void; resetOrbit:()=> void; zoomIn:()=> void; zoomOut:()=> void; resetZoom:()=> void; setZoom:(a: number)=> void; addSketchShape:(a: CutShape)=> void; clearSketch:()=> void; moveSketch:(a: number,b: number)=> void; rotateSketch:(a: number)=> void; applySketch:()=> void; movePiece:(a: string,b: number,c: number)=> void; rotatePiece:(a: string,b: number)=> void; deleteSelectedPieces:()=> void; joinSelectedPieces:()=> void; saveProject:()=> void }

const clamp = (n: number, min: number, max: number) => Math.max(min, Math.min(max, n))
export const useUIStore = create<UIState>((set, get) => ({
  mode: 'compose', tab: 'layers', tool: 'Select', selected: 'foreground', selectedPieces: [], sketch: [], dialog: null, time: 4.2, playing: false, grid: true, safeFrame: true, material: 'White paper', expanded: {}, keyframes: [], sceneLayers: cloneLayers(), orbit: {x:-18,y:18}, zoom: 1, reorderMode: saved?.reorderMode ?? 'cascade', saveStatus: 'saved',
  setMode: mode => set({ mode }), setTab: tab => set({ tab }), setTool: tool => set({ tool }), select: selected => set({ selected, selectedPieces: [] }), togglePieceSelection: (id, shift) => set(s => ({ selectedPieces: shift ? (s.selectedPieces.includes(id) ? s.selectedPieces.filter(x => x !== id) : [...s.selectedPieces, id]) : [id] })), setDialog: dialog => set({ dialog }), setTime: time => set({ time: clamp(time,0,12)}), togglePlaying: () => set(s => ({ playing: !s.playing })), toggleGrid: () => set(s => ({ grid: !s.grid })), toggleSafe: () => set(s => ({ safeFrame: !s.safeFrame })), setMaterial: material => set({ material }), toggleExpanded: id => set(s => ({ expanded: { ...s.expanded, [id]: !s.expanded[id] } })), toggleKey: id => set(s => ({ keyframes: s.keyframes.includes(id) ? s.keyframes.filter(k => k !== id) : [...s.keyframes, id] })),
  addLayer: () => set(s => s.sceneLayers.length >= 3 ? s : { sceneLayers: [...s.sceneLayers, { id: `layer-${Date.now()}`, name: `Layer ${s.sceneLayers.length + 1}`, depth: 0, color: '#ebb57b', visible: true, transform: { x:0, y:0, rotation:0, width:50, height:50, opacity:100}, cuts:[], pieces:[]}], saveStatus:'unsaved' }),
  removeLayer: id => set(s => ({ sceneLayers: s.sceneLayers.filter(l=>l.id!==id), selected: s.selected===id ? '' : s.selected, saveStatus:'unsaved' })),
  setLayerDepth: (id,depth) => set(s => ({ sceneLayers: s.sceneLayers.map(l=>l.id===id ? { ...l, depth: clamp(depth,-600,1200) } : l), saveStatus:'unsaved' })),
  setLayerTransform: (id,field,value) => set(s => ({ sceneLayers: s.sceneLayers.map(l=>l.id===id ? { ...l, transform: { ...l.transform, [field]: clamp(value, field==='opacity'?0:-1000, field==='opacity'?100:1000) } } : l), saveStatus:'unsaved' })),
  toggleLayerVisibility: id => set(s => ({ sceneLayers: s.sceneLayers.map(l=>l.id===id?{ ...l, visible:!l.visible }:l), saveStatus:'unsaved'})), renameLayer: (id,name) => set(s => ({ sceneLayers: s.sceneLayers.map(l=>l.id===id?{ ...l, name: name.slice(0,32)||'Untitled Layer'}:l), saveStatus:'unsaved'})),
  setLayerColor: (id,color) => set(s => ({ sceneLayers: s.sceneLayers.map(l=>l.id===id?{ ...l, color }:l), saveStatus:'unsaved'})),
  reorderLayer: (a,b) => set(s => { const from=s.sceneLayers.findIndex(l=>l.id===a); const to=s.sceneLayers.findIndex(l=>l.id===b); if(from<0 || to<0 || from===to) return s; const slots=s.sceneLayers.map(l=>l.depth); let next=[...s.sceneLayers]; const [m]=next.splice(from,1); next.splice(to,0,m); if(s.reorderMode === "cascade") next=next.map((l,i)=>({ ...l, depth:slots[i] })); else { const i=next.findIndex(l=>l.id===a); const before=next[i-1], after=next[i+1]; next[i]={ ...next[i], depth: before && after ? (before.depth+after.depth)/2 : before ? before.depth-100 : after ? after.depth+100 : 0 }; } const back=Math.min(...next.map(l=>l.depth)); return { sceneLayers:next.map(l=>({ ...l,depth:l.depth-back })),saveStatus:"unsaved"} }), setReorderMode: reorderMode => set({ reorderMode, saveStatus:'unsaved'}), setOrbit: orbit => set({ orbit }), resetOrbit: () => set({ orbit: {x:-18,y:18} }), zoomIn:()=> set(s=>({zoom: clamp(s.zoom+.1,.5,1.7)})), zoomOut:()=>set(s=>({ zoom: clamp(s.zoom-.1,.5,1.7)})), resetZoom:()=>set({ zoom:1}), setZoom: zoom=>set({ zoom: clamp(zoom,.5,1.7)}),
  addSketchShape: shape => set(s=>({ sketch: [...s.sketch, shape] })), clearSketch: ()=>set({ sketch:[]}), moveSketch: (dx,dy)=>set(s=>({ sketch:s.sketch.map(shape=>({ ...shape, points:shape.points.map(point=>({x:clamp(point.x+dx,0,100),y:clamp(point.y+dy,0,100)})) })) })), rotateSketch: (angle)=>set(s=>{ if(!s.sketch.length) return s; const points=s.sketch.flatMap(shape=>shape.points); const cx=points.reduce((sum,p)=>sum+p.x,0)/points.length, cy=points.reduce((sum,p)=>sum+p.y,0)/points.length, rad=angle*Math.PI/180; return { sketch:s.sketch.map(shape=>({ ...shape, points:shape.points.map(p=>({ x:clamp(cx+(p.x-cx)*Math.cos(rad)-(p.y-cy)*Math.sin(rad),0,100), y:clamp(cy+(p.x-cx)*Math.sin(rad)+(p.y-cy)*Math.cos(rad),0,100) })) })) } }), applySketch: ()=> set(s=> { const layer = s.sceneLayers.find(l=>l.id===s.selected); if (!layer || !s.sketch.length) return s; const pieces = s.sketch.map((shape,i)=>({ id:`piece-${Date.now()}-${i}`, name: `Subcut ${(i+1)}`, shapes:[shape], x:0, y:0, rotation:0, visible:true })); return { sceneLayers: s.sceneLayers.map(l=>l.id===layer.id?{ ...l, cuts:[...(l.cuts??[]), ...s.sketch], pieces:[...(l.pieces??[]), ...pieces]}:l), selectedPieces: pieces.map(p=>p.id), sketch:[], saveStatus:'unsaved' } }),
  movePiece: (id,dx,dy) => set(s=>({ sceneLayers: s.sceneLayers.map(l=>({ ...l, pieces: l.pieces?.map(p=>p.id===id?{ ...p, x:p.x+dx, y:p.y+dy}:p)})), saveStatus:'unsaved'})), rotatePiece: (id,angle) => set(s=>({ sceneLayers:s.sceneLayers.map(l=>({ ...l, pieces:l.pieces?.map(p=>p.id===id?{ ...p, rotation:(p.rotation??0)+angle}:p)})), saveStatus:'unsaved'})), deleteSelectedPieces: ()=> set(s=>({ sceneLayers:s.sceneLayers.map(l=>({...l,pieces:l.pieces?.filter(p=>!s.selectedPieces.includes(p.id))})), selectedPieces:[], saveStatus:'unsaved'})), joinSelectedPieces: ()=> set(s=> { if (s.selectedPieces.length < 2) return s; let joined=''; const sceneLayers=s.sceneLayers.map(l=>{ const picks=l.pieces?.filter(p=>s.selectedPieces.includes(p.id))??[]; if (picks.length<2) return l; joined=`join-${Date.now()}`; const first=picks[0]; return {...l, pieces:[...(l.pieces?? []).filter(p=>!s.selectedPieces.includes(p.id)), {id:joined,name:`Joined ${picks.length} pieces`, shapes:picks.flatMap(p=>p.shapes), x:first.x,y:first.y,visible:true}]} }); return { sceneLayers,selectedPieces:joined?[joined]:[],saveStatus:'unsaved'} }),
  saveProject: () => { const s=get(); window.localStorage.setItem('papercut.prototype.project.v1', JSON.stringify({ version:2, sceneLayers: s.sceneLayers, reorderMode: s.reorderMode })); set({ saveStatus:'saved'}) }
}))
